 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/ayekilua:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/ayekilua:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'ayekilua-service'
   - '--image'
   - 'gcr.io/$PROJECT_ID/ayekilua:$COMMIT_SHA'
   - '--region'
   - 'us-east1'
   - '--platform'
   - 'managed'
   - '--set-env-vars'
   - 'SERVER_KEY="${_SERVER_KEY}"'
 images:
 - 'gcr.io/$PROJECT_ID/ayekilua:$COMMIT_SHA'